name: Deploy Lambda

on:
  workflow_dispatch:
  push:
    branches:
      - '*' # Monitorea todas las ramas para el build y lint

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.7'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  lint:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.7'

      - name: Install ruff
        run: pip install ruff

      - name: Run ruff
        run: ruff check .

  deploy_test:
    needs: lint
    if: github.ref != 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.7'

      - name: Install AWS CLI
        run: pip install awscli

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Zip function for test
        run: |
          zip -r function.zip . -x "*/__pycache__/*" "*.pyc"

      - name: Deploy to Lambda (Test)
        run: aws lambda update-function-code --function-name ${{ secrets.AWS_LAMBDA_NAME_TEST }} --zip-file fileb://function.zip

  deploy_prod:
    needs: lint
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.7'

      - name: Install AWS CLI
        run: pip install awscli

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Zip function for production
        run: |
          zip -r function.zip . -x "*/__pycache__/*" "*.pyc"

      - name: Deploy to Lambda (Production)
        run: aws lambda update-function-code --function-name ${{ secrets.AWS_LAMBDA_NAME_PROD }} --zip-file fileb://function.zip
